/** Trechos reais (ementa) para comparação semântica — substitua por export do STJ em produção. */
export const STJ_REFERENCE_SNIPPETS: string[] = [
  "EMENTA: PROCESSUAL CIVIL. AGRAVO INTERNO NO AGRAVO EM RECURSO ESPECIAL. AÇÃO DE INDENIZAÇÃO POR DANOS MORAIS E MATERIAIS. ATRASO NA ENTREGA DE IMÓVEL. PRETENSÃO DE DANO MORAL IN RE IPSA. IMPOSSIBILIDADE. NECESSIDADE DE COMPROVAÇÃO. SÚMULA 7/STJ.",
  "EMENTA: ADMINISTRATIVO. PROCESSUAL CIVIL. SERVIDOR PÚBLICO. PENSÃO POR MORTE. REVISÃO. TERMO INICIAL. PRESCRIÇÃO.",
  "EMENTA: TRIBUTÁRIO. EXECUÇÃO FISCAL. PRESCRIÇÃO INTERCORRENTE. TERMO INICIAL. CIÊNCIA DA FAZENDA PÚBLICA. SÚMULA 10/STJ.",
  "EMENTA: DIREITO PENAL. HABEAS CORPUS. TRÁFICO DE DROGAS. DOSIMETRIA. CAUSA DE DIMINUIÇÃO. QUANTIDADE DE DROGA.",
  "EMENTA: PROCESSUAL CIVIL. RECURSO ESPECIAL. AÇÃO RESCISÓRIA. VIOLAÇÃO A LITERAL DISPOSIÇÃO DE LEI. NÃO OCORRÊNCIA.",
  "EMENTA: CIVIL. AGRAVO INTERNO NO AGRAVO EM RECURSO ESPECIAL. USUCAPIÃO. POSSE. ANIMUS DOMINI. COMPROVAÇÃO.",
  "EMENTA: TRIBUTÁRIO. ICMS. BASE DE CÁLCULO. INCLUSÃO DO IPI. IMPOSSIBILIDADE.",
  "EMENTA: PENAL. RECURSO ORDINÁRIO EM HABEAS CORPUS. LESÃO CORPORAL. VIOLÊNCIA DOMÉSTICA. REPRESENTAÇÃO. RENÚNCIA.",
];
